cluster.name: elk
discovery.zen.ping.unicast.hosts: ["master:9200", "data:9200"]
http.host: 0.0.0.0
# Uncomment the following lines for a production cluster deployment
transport.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 1
