cluster.name: elk
discovery.zen.ping.unicast.hosts: ["master:9200", "data:9200"]
network.host: [_eth0_,_local_]

# Uncomment the following lines for a production cluster deployment
#transport.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 1
